const pulgin={
    el:null,
    init:function(el){
        this.el=el;
    },
    connect:function(name,pwd){
        try{
           this.el.StartConnect(name,pwd);
        }
        catch(e){
            console.log(e);
        }
    },
    Disconnect:function(){
        try{
            this.el.Disconnect();
         }
         catch(e){
             console.log(e);
         }
    },
    setVolume:function(num){
        try{
           this.el.setVolume(num);
        }
        catch(e){
            console.log(e);
        }
    },
    setBrightness:function(num){
        try{
           this.el.setBrightness(num);
        }
        catch(e){
            console.log(e);
        }
    },
    start:function(){
        try{
            this.el.start();
         }
         catch(e){
             console.log(e);
         }
    },
    StartScan:function(){
        try{
            this.el.StartScan();
         }
         catch(e){
             console.log(e);
         }
    }
}
export default pulgin